export { default as Index } from './layout/Master'
export { default as NavBar } from './layout/NavBar'
export { default as Footer } from './layout/Footer'
export { default as Spinner } from './layout/Spinner'
export { default as NotFoundPage } from './layout/NotFoundPage'
export { default as Calender } from './calenders/Calender'
export { default as Gregorian } from './calenders/Gregorian'
export { default as Hijri } from './calenders/Hijri'
